apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: learning-tracker
  name: learning-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learning-tracker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: learning-tracker
    spec:
      containers:
      - image: europe-west4-docker.pkg.dev/xebia-k8s-training-1/ghcr/tsclabs-eu/learning-tracker:v1.0.5
        name: learning-tracker
        resources: {}
status: {}
